New f: 12
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
